// src/keywords.js
const keywords = [
  "Chest", "Back", "Legs", "Shoulders", "Arms", "Biceps", "Triceps", "Abs", 
  "Core", "Glutes", "Hamstrings", "Quadriceps", "Calves", "Forearms", "Legs", "Leg",
  "Deltoids", "Lats", "Strength", "Cardio", "Endurance", "Flexibility", 
  "HIIT", "Pilates", "Yoga", "CrossFit", "Aerobics", "Bodybuilding", 
  "Powerlifting", "Stretching", "Resistance Training", "Calisthenics", 
  "Bench Press", "Squat", "Deadlift", "Pull-up", "Push-up", "Row", "Lunge", 
  "Plank", "Burpee", "Sit-up", "Crunch", "Dip", "Shoulder Press", 
  "Overhead Press", "Bicep Curl", "Tricep Extension", "Leg Press", 
  "Chest Fly", "Cable Crossover", "Barbell Curl", "Dumbbell Curl", 
  "Dead Hang", "Sets", "Reps", "Weight", "Max", "Personal Record", 
  "Failure", "Spotter", "Form", "Warm-up", "Cool-down", "Rest Day", 
  "Active Recovery", "DOMS", "Barbell", "Dumbbell", "Kettlebell", 
  "Resistance Band", "Treadmill", "Elliptical", "Rowing Machine", 
  "Exercise Ball", "Bench", "Squat Rack", "Smith Machine", "Pull-up Bar", 
  "TRX", "Foam Roller", "Split", "Full-Body", "Upper-Lower", "Push-Pull", 
  "Bro Split", "5x5", "Superset", "Dropset", "Giant Set", "Circuit", 
  "Tabata", "Periodization", "Protein", "Carbohydrates", "Fats", 
  "Vitamins", "Minerals", "Fiber", "Sugars", "Chicken", "Beef", "Fish", 
  "Tuna", "Salmon", "Turkey", "Pork", "Tofu", "Tempeh", "Eggs", "Lentils", 
  "Chickpeas", "Quinoa", "Beans", "Protein Powder", "Rice", "Bread", 
  "Pasta", "Oats", "Potatoes", "Sweet Potatoes", "Cereal", "Corn", 
  "Fruits", "Vegetables", "Avocado", "Nuts", "Seeds", "Olive Oil", 
  "Coconut Oil", "Peanut Butter", "Almond Butter", "Fish Oil", "Omega-3", 
  "Chia Seeds", "Flaxseeds", "Keto", "Paleo", "Vegan", "Vegetarian", 
  "Low-Carb", "High-Protein", "Mediterranean", "Carnivore", "Plant-Based", 
  "Gluten-Free", "Dairy-Free", "Whole30", "Intermittent Fasting", 
  "Calories", "Macronutrients", "Micronutrients", "Meal Prep", "Portion", 
  "Serving Size", "Hydration", "Electrolytes", "Supplements", 
  "Multivitamin", "Pre-Workout", "Post-Workout", "Junk Food", 
  "Fast Food", "Sugar", "Sweets", "Soda", "Candy", "Chips", 
  "Processed Food", "Artificial Sweeteners", "High Fructose Corn Syrup", 
  "Weight Loss", "Fat Loss", "Muscle Gain", "Bulking", "Cutting", 
  "Toning", "Lean", "Conditioning", "Shredding", "Body Recomposition", 
  "BMI", "Body Fat", "Calories Burned", "Heart Rate", "Resting Heart Rate", 
  "VO2 Max", "Metabolism", "BMR", "TDEE", "Obesity", "Diabetes", 
  "High Blood Pressure", "Cholesterol", "Cardiovascular", "Osteoporosis", 
  "Arthritis", "Inflammation", "Gut Health", "Hormones", "Sleep", 
  "Rest", "Massage", "Stretching", "Ice Bath", "Heat Therapy", 
  "Recovery Drink", "Protein Shake", "Injury Prevention", "Overtraining", 
  "Motivation", "Discipline", "Consistency", "Progress", "Goals", 
  "Mindset", "Accountability", "Visualization", "Routine", "Streak", 
  "Personal Best", "Milestone"
];

export default keywords;
