// src/reportWebVitals.js
// This file is typically generated by Create React App.
// It sets up the reporting of Web Vitals metrics.
// These metrics are useful for understanding the performance of your application.

const reportWebVitals = (onPerfEntry) => {
  // Check if onPerfEntry is a function before proceeding
  if (onPerfEntry && onPerfEntry instanceof Function) {
    // Dynamically import the 'web-vitals' library
    import("web-vitals")
      .then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
        // Call the respective function for each web vital metric
        getCLS(onPerfEntry); // Cumulative Layout Shift
        getFID(onPerfEntry); // First Input Delay
        getFCP(onPerfEntry); // First Contentful Paint
        getLCP(onPerfEntry); // Largest Contentful Paint
        getTTFB(onPerfEntry); // Time to First Byte
      })
      .catch((err) => {
        // Handle any errors during the dynamic import
        console.error("Error importing web-vitals:", err);
      });
  }
};

export default reportWebVitals;
